# Generated by Django 3.0.5 on 2020-05-08 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaintingTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.TextField()),
                ('creator', models.TextField()),
                ('claimedAmt', models.IntegerField()),
                ('availableForBid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BidTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalBidAmt', models.IntegerField()),
                ('name', models.TextField()),
                ('paintingTable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PaintingTable')),
            ],
        ),
    ]
