# Generated by Django 3.0.5 on 2020-05-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidtable',
            old_name='paintingTable',
            new_name='paintingRef',
        ),
        migrations.AddField(
            model_name='paintingtable',
            name='paintingName',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paintingtable',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
