# Generated by Django 3.0.5 on 2020-05-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200509_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidtable',
            name='finalBidAmt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='paintingtable',
            name='claimedAmt',
            field=models.FloatField(),
        ),
    ]
